### ISSUE TITLE
viability for steppers and Beaglebone Green Wireless

### ISSUE THREAD

**Issue by troywweber7** [petermancuso/bbb#1]
Hello, I was hoping someone familiar with this library might be able to answer a few questions:

1. Can this library apply on the SeeedStudio BeagleBone Green Wireless?
2. Does this library use the device-tree overlay and file i/o to toggle GPIO pins, or can it handle higher-frequency GPIO i/o? i.e., could it be used to control a stepper motor driver (where I have to toggle the step pin many timers per millisecond)?

Thanks ahead of time for any input.

**Comment by petermancuso** [comment]
1. This code will work on any BeagleBone with the same memory configuration. I don't have a BB Green to test. Different memory configuration will require tweaks of the memory map file. 
2. Device tree overlay allows you to change the function of IO pins. Like turning on PWM for a supported pin, or making that same pin digital IO. On the performance side, this library uses memory mapped values, so you can achieve much high frequencies than reading values from the Linux file system (which is what a lot of wrapper libraries use). 

On another note. There is a more complete C++ memory mapped solution on GitHub. I recommend you ultimately use that library, as development on this project has halted. However, my library is rather simple to understand and implement. Follow the instructions on Derek Molloy's  web site for device tree overlays and then follow the setup instructions. 

I use dedicated ICs for stepper motor control/interfacing. Adafruit sells servo/stepper kits for RPi....they may have libraries for BeagleBone too. Hope this helps.
